commands:

  - type: download
    url: https://weechat.org/files/scripts/vimode.py
    dst: '<%= get_var!(:weechat_dir, type: :dir).join("python", "vimode.py") %>'
    only:
      features:
        - weechat

  - type: download
    url: https://weechat.org/files/scripts/colorize_nicks.py
    dst: '<%= get_var!(:weechat_dir, type: :dir).join("python", "colorize_nicks.py") %>'
    only:
      features:
        - weechat

elems:

  - src: elems/(.+)$
    dst: '<%= get_var!(:weechat_dir, type: :dir) %>/<1>'
    only:
      features:
        - weechat


# vim: set filetype=eruby.yaml :
